/**
 * --------
 * Currency
 * --------
 */
var Currency = new Object();
/** @static */
Currency.currencies = ['GBP', 'USD', 'EUR', 'JPY', 'AED', 'AFN', 'ALL', 'ANG', 'AOA', 'ARS', 'ATS', 'AUD', 'AWG', 'BBD', 'BDT', 'BEF', 'BGN', 'BHD', 'BIF', 'BMD', 'BND', 'BOB', 'BRL', 'BSD', 'BTN', 'BWP', 'BZD', 'CAD', 'CDF', 'CHF', 'CLP', 'CNY', 'COP', 'CRC', 'CUP', 'CVE', 'CYP', 'CZK', 'DEM', 'DJF', 'DKK', 'DOP', 'DZD', 'ECS', 'EEK', 'EGP', 'ESP', 'ETB', 'FIM', 'FJD', 'FRF', 'GHC', 'GIP', 'GMD', 'GNF', 'GRD', 'GTQ', 'GWP', 'GYD', 'HKD', 'HNL', 'HRK', 'HTG', 'HUF', 'IDR', 'IEP', 'ILS', 'INR', 'IRR', 'ISK', 'ITL', 'JMD', 'JOD', 'KES', 'KMF', 'KRW', 'KWD', 'KYD', 'LAK', 'LBP', 'LKR', 'LRD', 'LSL', 'LTL', 'LUF', 'LVL', 'MAD', 'MGA', 'MMK', 'MNT', 'MOP', 'MRO', 'MTL', 'MUR', 'MVR', 'MWK', 'MXN', 'MYR', 'MZM', 'NGN', 'NIO', 'NLG', 'NOK', 'NPR', 'NZD', 'OMR', 'PAB', 'PEN', 'PGK', 'PHP', 'PKR', 'PLN', 'PTE', 'PYG', 'QAR', 'ROL', 'RUB', 'RWF', 'SAR', 'SBD', 'SCR', 'SDD', 'SEK', 'SGD', 'SHP', 'SIT', 'SKK', 'SLL', 'SOS', 'SRD', 'STD', 'SVC', 'SYP', 'SZL', 'THB', 'TND', 'TOP', 'TRY', 'TTD', 'TWD', 'TZS', 'UAH', 'UGX', 'UYU', 'VEB', 'VND', 'VUV', 'WST', 'XAF', 'XCD', 'XDR', 'XOF', 'XPF', 'YER', 'ZAR', 'ZMK', 'ZWD'];
/** @static */
Currency.currencyNames = ['British Pound', 'US Dollar', 'Euro', 'Japanese Yen', 'United Arab Emirates Dirham',
'Afghanistan Afghani',
'Albanian Lek',
'Netherlands Ant. Guilder',
'Angola Kwanza',
'Argentine Peso',
'Austrian Schilling',
'Australian Dollar',
'Aruba Guilder',
'Barbados Dollar',
'Bangladesh Taka',
'Belgian Franc',
'Bulgarian Lev',
'Bahraini Dinar',
'Burundi Franc',
'Bermudan Dollar',
'Brunei Dollar',
'Bolivian Boliviano',
'Brazilian Real',
'Bahamas Dollar',
'Bhutan Ngultrum',
'Botswana Pula',
'Belize Dollar',
'Canadian Dollar',
'Congolese Franc',
'Swiss Franc',
'Chilean Peso',
'Chinesyuan Renminbi',
'Colombian Peso',
'Costa Rican Colon',
'Cuba Peso',
'Cape Verde Escudo',
'Cyprus Pound',
'Czech Koruna',
'German Mark',
'Djibouti Franc',
'Danish Krone',
'Domican Republic Peso',
'Algerian Dinar',
'Ecuadorian Sucre',
'Estonian Kroon',
'Egyptian Pound',
'Spanish Peseta',
'Ethiopian Birr',
'Finnish Markka',
'Fiji Dollar',
'French Franc',
'Ghana Cedi',
'Gibraltar Pound',
'Ganbian Dalasi',
'Guinea Republic Franc',
'Greek Drachma',
'Guatemala Quetzal',
'Guinea Bissau Peso',
'Guyana Dollar',
'Hong Kong Dollar',
'Honduras Lempira',
'Croatian Kuna',
'Haiti Gourde',
'Hungarian Forint',
'Indonesian Rupiah',
'Irish Punt',
'Israeli Shekel',
'Indian Rupee',
'Iranian Real',
'Iceland Krona',
'Italian Lira',
'Jamican Dollar',
'Jordanian Dinar',
'Kenyan Schilling',
'Comoros Franc',
'Korean Won',
'Kuwaiti Dinar',
'Cayman Islands Dollar',
'Laos Kip',
'Lebanese Pound',
'Sri Lankan Rupee',
'Liberia Dollar',
'Lesotho Loti',
'Lithuanian Litas',
'Luxemburg Franc',
'Latvia Lat',
'Morrocan Diham',
'Madagascar Ariary',
'Mynamar Kyat',
'Mongolian Tugrit',
'Macao Pataca',
'Mautitanian Ouguiya',
'Maltese Lira',
'Mauritius Rupee',
'Maldives Rufiyan',
'Malawi Kwaacha',
'Mexican Nuevo Peso',
'Malaysian Ringgit',
'Mozambique Metical',
'Nigerian Naira',
'Nicaraguan Cordoba',
'Dutch Guilder',
'Norwegian Krone',
'Nepal Rupee',
'New Zealand Dollar',
'Omani Rial',
'Panama Balboa',
'Peru Nuevo Sol',
'Papua New Guinea Kina',
'Philippini Peso',
'Pakistani Rupee',
'Polish Zloty',
'Portugese Escudo',
'Paraguay Guarani',
'Qatari Rial',
'Romania Leu',
'Russian Ruble',
'Rwanda Franc',
'Saudi Rial',
'Solomon Islands Dollar',
'Seychelles Rupee',
'Sudanese Dinar',
'Swedish Krona',
'Singapore Dollar',
'Saint Helenian Pound',
'Slovenian Tolar',
'Slovak Koruna',
'Sierra Leone Leone',
'Somalian Schilling',
'Suriname Dollar',
'Sao Tome & Principe Dobra',
'El Salvador Colon',
'Syrian Pound',
'Swaziland Lilangeni',
'Thai Baht',
'Tunisian Dinar',
'Tongan Pa\'anga',
'Turkish New Lira',
'Trinidad & Tobago Dollar',
'Taiwan New Dollar',
'Tanzanian Schilling',
'Ukraine Karbovanet',
'Ugandan Shilling',
'Uruguayan Peso',
'Venezuelan Bolivar',
'Vietnam Dong',
'Vanuatu Vatu',
'Samoan Tala',
'Central Africa CFA franc (XAF)',
'East Caribbean Dollar',
'Special Drawing Rights',
'West African CFA franc (XOF)',
'French Pacific Island Franc',
'Yemeni rial',
'South African Rand',
'Zambian Kwacha',
'Zimbabwean Dollar'];